Repository prgrms-be-devcourse/BE-03-BlackDogBucks, pull requests merged in 2023-02, with the labels that each got.

#93 [#13] 주문 수락, 거절 기능 구현
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/common/util/Location.java
  src/main/java/com/prgrms/bdbks/domain/coupon/converter/CouponMapper.java
  src/main/java/com/prgrms/bdbks/domain/order/api/OrderController.java
  src/main/java/com/prgrms/bdbks/domain/order/dto/OrderAcceptRequest.java
  src/main/java/com/prgrms/bdbks/domain/order/dto/OrderRejectRequest.java
  src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
  src/main/java/com/prgrms/bdbks/domain/order/exception/AlreadyProgressOrderException.java
  src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
  src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/order/service/OrderService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/star/service/DefaultStarService.java
  src/main/java/com/prgrms/bdbks/domain/star/service/StarFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/star/service/StarService.java
  src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
  src/main/java/com/prgrms/bdbks/domain/store/repository/StoreRepository.java
  src/main/java/com/prgrms/bdbks/domain/store/service/DefaultStoreService.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/UserAuthority.java
  src/test/java/com/prgrms/bdbks/domain/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/service/DefaultOrderServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/order/service/OrderFacadeServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/star/entity/StarTest.java
  src/test/java/com/prgrms/bdbks/domain/store/repository/StoreRepositoryTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/OrderObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/user/api/UserControllerMvcTest.java
  src/test/resources/application-test.yml
Labels: :sparkles: feat

#94 [#24] 결제를 취소한다.
  src/main/java/com/prgrms/bdbks/common/exception/CouponUnUsedException.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardRefundResponse.java
  src/main/java/com/prgrms/bdbks/domain/card/entity/Card.java
  src/main/java/com/prgrms/bdbks/domain/card/service/CardService.java
  src/main/java/com/prgrms/bdbks/domain/card/service/DefaultCardService.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponRefundResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/entity/Coupon.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/CouponService.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponService.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderRefundPayment.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentRefundResult.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentSearchResponse.java
  src/main/java/com/prgrms/bdbks/domain/payment/entity/Payment.java
  src/main/java/com/prgrms/bdbks/domain/payment/repository/PaymentRepository.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentService.java
  src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/entity/CouponTest.java
  src/test/java/com/prgrms/bdbks/domain/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#95 [#17, 18] 유저 권한 기능 추가
  src/main/java/com/prgrms/bdbks/BlackDogBucksApplication.java
  src/main/java/com/prgrms/bdbks/common/exception/DuplicateInsertException.java
  src/main/java/com/prgrms/bdbks/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/bdbks/common/exception/NonActivatedUserException.java
  src/main/java/com/prgrms/bdbks/config/jwt/JwtConfigure.java
  src/main/java/com/prgrms/bdbks/config/security/SecurityConfig.java
  src/main/java/com/prgrms/bdbks/config/web/WebConfig.java
  src/main/java/com/prgrms/bdbks/domain/user/api/AuthController.java
  src/main/java/com/prgrms/bdbks/domain/user/api/UserController.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/StoreUserChangeRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserFindResponse.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/Authority.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/UserAdapter.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/UserAuthority.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/CustomUserDetails.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/JwtAuthenticationFilter.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/JwtSecurityConfig.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/TokenProvider.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/AuthorityRepository.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/UserAuthorityRepository.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/bdbks/domain/user/role/Role.java
  src/main/java/com/prgrms/bdbks/domain/user/service/AuthService.java
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/bdbks/domain/user/service/UserService.java
  src/test/java/com/prgrms/bdbks/domain/testutil/StoreObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/user/api/AuthControllerIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/user/api/UserControllerIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/user/api/UserControllerMvcTest.java
  src/test/java/com/prgrms/bdbks/domain/user/entity/UserTest.java
  src/test/java/com/prgrms/bdbks/domain/user/service/DefaultUserServiceTest.java
  src/test/resources/test_sql/user.sql
Labels: :recycle: refactor

#97 [#96] 결제 충전, 환불 기능, 별 쿠폰 변환 기능 주문 Facade 안으로 이동
  src/main/java/com/prgrms/bdbks/domain/card/api/CardController.java
  src/main/java/com/prgrms/bdbks/domain/coupon/api/CouponController.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponRefundResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSaveResponse.java
  src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/star/service/StarFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/test/java/com/prgrms/bdbks/domain/card/api/CardControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/api/CouponControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/service/OrderFacadeServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeServiceTest.java
Labels: :white_check_mark: test, :recycle: refactor

#98 refactor : Security 테스트 사전작업 간소화
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/test/java/com/prgrms/bdbks/WithMockCustomUser.java
  src/test/java/com/prgrms/bdbks/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/prgrms/bdbks/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/user/api/AuthControllerIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/user/api/UserControllerIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/user/api/UserControllerMvcTest.java
  src/test/resources/test_sql/user.sql
Labels: :recycle: refactor

#100 [#99] Card ID Generator를 등록한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/config/jpa/JpaConfig.java
  src/main/java/com/prgrms/bdbks/domain/card/converter/CardMapper.java
  src/main/java/com/prgrms/bdbks/domain/card/entity/Card.java
  src/main/java/com/prgrms/bdbks/domain/card/repository/CardIdGenerator.java
  src/main/java/com/prgrms/bdbks/domain/card/repository/DefaultRandomGenerator.java
  src/main/java/com/prgrms/bdbks/domain/card/repository/RandomNumberGenerator.java
  src/main/java/com/prgrms/bdbks/domain/card/service/DefaultCardService.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/test/java/com/prgrms/bdbks/WithMockCustomUser.java
  src/test/java/com/prgrms/bdbks/domain/card/api/CardControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/card/repository/CardIdGeneratorTest.java
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/api/CouponControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/service/DefaultOrderServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
Labels: :recycle: refactor
