Repository prgrms-be-devcourse/BE-03-BlackDogBucks, pull requests merged in 2023-01, with the labels that each got.

#4 [#3] template 추가
  .github/ISSUE_TEMPLATE/bakclog-template.md
  .github/pull_request_template.md
Labels: :memo: chore

#29 [#10] 상품 추가 기능을 구현한다.
  build.gradle
  src/main/java/com/prgrms/bdbks/domain/item/entity/BeverageOption.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/DefaultOption.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/Item.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/ItemCategory.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/ItemType.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/OptionPrice.java
  src/main/java/com/prgrms/bdbks/global/util/UrlValidator.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/DefaultOptionTest.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/ItemCategoryTest.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/ItemTest.java
Labels: :sparkles: feat

#30 [#2] 사용자(user) 엔티티 생성
  build.gradle
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserLoginRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/role/Role.java
  src/test/java/com/prgrms/bdbks/domain/user/entity/UserTest.java
Labels: :sparkles: feat

#31 refactor : engName -> englishName 필드명 변경 및 예외 메시지 한글화
  src/main/java/com/prgrms/bdbks/domain/item/entity/BeverageOption.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/DefaultOption.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/Item.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/ItemCategory.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/ItemType.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/ItemCategoryTest.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/ItemTest.java
Labels: :recycle: refactor

#35 [#25] 매장 Entity 구현
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
  src/test/java/com/prgrms/bdbks/domain/store/entity/StoreTest.java
Labels: :sparkles: feat

#38 사용자 환경 관련 파일 제외
  .gitignore
  src/main/resources/application-db.yml
  src/main/resources/application.yml
  src/test/resources/application-test.yml
Labels: :wrench: config

#40 #[10 ] 상품 추가기능을 구현한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/config/security/SecurityConfig.java
  src/main/java/com/prgrms/bdbks/domain/item/api/ItemController.java
  src/main/java/com/prgrms/bdbks/domain/item/dto/DefaultOptionCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/item/dto/ItemCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/DefaultOption.java
  src/main/java/com/prgrms/bdbks/domain/item/entity/Item.java
  src/main/java/com/prgrms/bdbks/domain/item/service/DefaultItemService.java
  src/main/java/com/prgrms/bdbks/domain/item/service/DefaultOptionService.java
  src/main/java/com/prgrms/bdbks/domain/item/service/ItemFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/item/service/ItemOptionService.java
  src/main/java/com/prgrms/bdbks/domain/item/service/ItemService.java
  src/test/java/com/prgrms/bdbks/domain/item/api/ItemControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/item/api/ItemControllerWebMvcTest.java
  src/test/java/com/prgrms/bdbks/domain/item/entity/DefaultOptionTest.java
  src/test/java/com/prgrms/bdbks/domain/item/service/DefaultItemServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/item/service/DefaultOptionServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/item/service/ItemFacadeServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/ItemObjectProvider.java
Labels: :sparkles: feat

#51 [#9] 카드 엔티티 추가
  src/main/java/com/prgrms/bdbks/domain/card/entity/Card.java
  src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/CardObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#49 [#9] 쿠폰 엔티티 추가
  src/main/java/com/prgrms/bdbks/domain/coupon/entity/Coupon.java
  src/test/java/com/prgrms/bdbks/domain/coupon/entity/CouponTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/CouponObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#50 [#9] 별 엔티티 추가
  src/main/java/com/prgrms/bdbks/domain/star/entity/Star.java
  src/test/java/com/prgrms/bdbks/domain/star/entity/StarTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/StarObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#52 [#9] 결제 엔티티 추가
  src/main/java/com/prgrms/bdbks/domain/payment/entity/Payment.java
  src/main/java/com/prgrms/bdbks/domain/payment/entity/PaymentStatus.java
  src/main/java/com/prgrms/bdbks/domain/payment/entity/PaymentType.java
  src/test/java/com/prgrms/bdbks/domain/payment/entity/PaymentTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/PaymentObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/StarObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#53 [#22, #32] 카드 전체조회, 단건조회, 금액충전
  src/main/java/com/prgrms/bdbks/domain/card/converter/CardMapper.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardChargeRequest.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardChargeResponse.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardSearchResponse.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardSearchResponses.java
  src/main/java/com/prgrms/bdbks/domain/card/repository/CardRepository.java
  src/main/java/com/prgrms/bdbks/domain/card/service/CardService.java
  src/main/java/com/prgrms/bdbks/domain/card/service/DefaultCardService.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/UserRepository.java
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/CardObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#48 [#17, #18] 사용자 회원가입, 로그인 기능 구현
  http/user.http
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/domain/user/controller/UserController.java
  src/main/java/com/prgrms/bdbks/domain/user/converter/UserMapper.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserFindResponse.java
  src/main/java/com/prgrms/bdbks/domain/user/dto/UserLoginRequest.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/UserAdapter.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/UserRepository.java
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/bdbks/domain/user/service/UserService.java
  src/test/java/com/prgrms/bdbks/domain/user/controller/UserControllerMvcTest.java
  src/test/java/com/prgrms/bdbks/domain/user/entity/UserTest.java
Labels: :sparkles: feat

#59 [#20, #56] 쿠폰 생성, 조회
  src/main/java/com/prgrms/bdbks/domain/coupon/converter/CouponMapper.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSaveResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSearchResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSearchResponses.java
  src/main/java/com/prgrms/bdbks/domain/coupon/repository/CouponRepository.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/CouponService.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponService.java
  src/test/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponIntegrationServiceTest.java
Labels: :sparkles: feat, :white_check_mark: test

#58 [#22,#23] 주문 결제, 카드 충전 기능 추가
  src/main/java/com/prgrms/bdbks/common/exception/PaymentException.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentChargeRequest.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentChargeResponse.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentOrderRequest.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentOrderResponse.java
  src/main/java/com/prgrms/bdbks/domain/payment/entity/Payment.java
  src/main/java/com/prgrms/bdbks/domain/payment/repository/PaymentRepository.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentService.java
  src/test/java/com/prgrms/bdbks/domain/payment/entity/PaymentTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/PaymentObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test

#61 [#18] feat : 유저 아이디로 유저 반환 기능 Service에 추가
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/bdbks/domain/user/service/UserService.java
Labels: :sparkles: feat

#62 [#22,#23] 주문 결제, 충전 결제 기능 추가
  src/main/java/com/prgrms/bdbks/common/exception/CouponAlreadyUsedException.java
  src/main/java/com/prgrms/bdbks/common/exception/PaymentException.java
  src/main/java/com/prgrms/bdbks/domain/card/dto/CardPayResponse.java
  src/main/java/com/prgrms/bdbks/domain/card/service/CardService.java
  src/main/java/com/prgrms/bdbks/domain/card/service/DefaultCardService.java
  src/main/java/com/prgrms/bdbks/domain/coupon/entity/Coupon.java
  src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/OrderPayment.java
  src/main/java/com/prgrms/bdbks/domain/payment/dto/PaymentOrderRequest.java
  src/main/java/com/prgrms/bdbks/domain/payment/entity/Payment.java
  src/main/java/com/prgrms/bdbks/domain/payment/model/PaymentResult.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/payment/service/PaymentService.java
  src/main/java/com/prgrms/bdbks/domain/star/converter/StarMapper.java
  src/main/java/com/prgrms/bdbks/domain/star/service/DefaultStarService.java
  src/main/java/com/prgrms/bdbks/domain/star/service/StarService.java
  src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/PaymentFacadeServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/star/service/StarServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/OrderObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test, :recycle: refactor

#64 [#63] 테스트 에러를 수정한다.
  src/main/java/com/prgrms/bdbks/domain/payment/entity/Payment.java
  src/main/java/com/prgrms/bdbks/domain/user/repository/UserRepository.java
  src/test/java/com/prgrms/bdbks/domain/order/entity/OrderTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/entity/PaymentTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/PaymentObjectProvider.java
Labels: :bug: fix, :recycle: refactor

#70 [#67, #69] 쿠폰 전체 조회, 미사용 쿠폰 조회 API를 개발한다.
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/domain/card/entity/Card.java
  src/main/java/com/prgrms/bdbks/domain/coupon/api/CouponController.java
  src/main/java/com/prgrms/bdbks/domain/coupon/converter/CouponMapper.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSaveResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/dto/CouponSearchResponse.java
  src/main/java/com/prgrms/bdbks/domain/coupon/entity/Coupon.java
  src/main/java/com/prgrms/bdbks/domain/coupon/repository/CouponRepository.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/CouponService.java
  src/main/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponService.java
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceSliceTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/api/CouponControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/repository/CouponRepositoryTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponIntegrationServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/payment/service/DefaultPaymentServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/CardObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/CouponObjectProvider.java
Labels: :sparkles: feat, :white_check_mark: test, :recycle: refactor

#73 [#72] JwtConfigure 빈 등록 실패 해결
  src/main/java/com/prgrms/bdbks/BlackDogBucksApplication.java
  src/main/java/com/prgrms/bdbks/config/jwt/JwtConfigure.java
  src/main/java/com/prgrms/bdbks/domain/user/jwt/TokenProvider.java
Labels: :bug: fix, :recycle: refactor

#77 [#76] ReadMe 파일을 만든다.
  README.md
Labels: :memo: chore

#84 [#26, #27, #66] 매장 등록, 구이름 조회, 거리 순 조회 API 개발
  http/store.http
  src/main/java/com/prgrms/bdbks/common/exception/PointParseException.java
  src/main/java/com/prgrms/bdbks/domain/store/api/StoreController.java
  src/main/java/com/prgrms/bdbks/domain/store/converter/StoreMapper.java
  src/main/java/com/prgrms/bdbks/domain/store/dto/StoreCreateRequest.java
  src/main/java/com/prgrms/bdbks/domain/store/dto/StorePointRequest.java
  src/main/java/com/prgrms/bdbks/domain/store/dto/StoreResponse.java
  src/main/java/com/prgrms/bdbks/domain/store/entity/Store.java
  src/main/java/com/prgrms/bdbks/domain/store/repository/StoreRepository.java
  src/main/java/com/prgrms/bdbks/domain/store/service/DefaultStoreService.java
  src/main/java/com/prgrms/bdbks/domain/store/service/StoreService.java
  src/main/java/com/prgrms/bdbks/domain/user/api/UserController.java
  src/main/java/com/prgrms/bdbks/global/util/Location.java
  src/main/resources/store.sql
  src/test/java/com/prgrms/bdbks/domain/store/api/StoreControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/store/repository/StoreRepositoryTest.java
Labels: :sparkles: feat

#86 [#85] 매장별 주문 리스트 조회 API 구현
  build.gradle
  src/docs/asciidoc/index.adoc
  src/main/java/com/prgrms/bdbks/common/dto/SliceResponse.java
  src/main/java/com/prgrms/bdbks/common/util/SliceUtil.java
  src/main/java/com/prgrms/bdbks/domain/order/api/OrderController.java
  src/main/java/com/prgrms/bdbks/domain/order/dto/OrderByStoreResponse.java
  src/main/java/com/prgrms/bdbks/domain/order/dto/OrderSearchRequest.java
  src/main/java/com/prgrms/bdbks/domain/order/dto/OrdersBy.java
  src/main/java/com/prgrms/bdbks/domain/order/entity/Order.java
  src/main/java/com/prgrms/bdbks/domain/order/entity/OrderStatus.java
  src/main/java/com/prgrms/bdbks/domain/order/repository/OrderSupport.java
  src/main/java/com/prgrms/bdbks/domain/order/repository/OrderSupportImpl.java
  src/main/java/com/prgrms/bdbks/domain/order/service/DefaultOrderService.java
  src/main/java/com/prgrms/bdbks/domain/order/service/OrderFacadeService.java
  src/main/java/com/prgrms/bdbks/domain/order/service/OrderService.java
  src/main/java/com/prgrms/bdbks/domain/store/service/StoreService.java
  src/test/java/com/prgrms/bdbks/domain/order/api/OrderControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/order/repository/OrderSupportImplTest.java
  src/test/java/com/prgrms/bdbks/domain/order/service/DefaultOrderServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/ItemObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
Labels: :sparkles: feat

#89 [#79] User가 매장 유저인지, 요청이 들어온 매장의 주인인지 확인하는 기능
  src/main/java/com/prgrms/bdbks/common/exception/GlobalExceptionHandler.java
  src/main/java/com/prgrms/bdbks/domain/user/converter/UserMapper.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/User.java
  src/main/java/com/prgrms/bdbks/domain/user/entity/UserAdapter.java
  src/main/java/com/prgrms/bdbks/domain/user/service/DefaultUserService.java
  src/main/java/com/prgrms/bdbks/domain/user/service/UserService.java
  src/test/java/com/prgrms/bdbks/domain/card/entity/CardTest.java
  src/test/java/com/prgrms/bdbks/domain/testutil/UserObjectProvider.java
  src/test/java/com/prgrms/bdbks/domain/user/entity/UserTest.java
Labels: :sparkles: feat

#90 fix : 메소드 시그니처 통일
  src/main/java/com/prgrms/bdbks/domain/store/service/DefaultStoreService.java
  src/main/java/com/prgrms/bdbks/domain/store/service/StoreService.java
Labels: :bug: fix

#92 [#91] Star, Coupon 테스트 에러 수정
  src/test/java/com/prgrms/bdbks/domain/card/service/DefaultCardServiceIntegrationTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/api/CouponControllerTest.java
  src/test/java/com/prgrms/bdbks/domain/coupon/service/DefaultCouponIntegrationServiceTest.java
  src/test/java/com/prgrms/bdbks/domain/star/entity/StarTest.java
Labels: :bug: fix, :recycle: refactor
